### ISSUE TITLE
Facebook still tracks middle- and right-clicked links in Firefox

### ISSUE THREAD

**Issue by bcyphers** [mgziminsky/FacebookTrackingRemoval#10]
Hi @mgziminsky,

First off, thanks for making a great extension! I work on Privacy Badger at EFF, and we're planning to incorporate parts of your code into PB to stop facebook link-tracking. That pull request is here: https://github.com/EFForg/privacybadger/pull/1993/files

The issue is this: In firefox, if you click a link with the middle (scroll wheel) or right mouse buttons, you can still see a POST request go out to https://www.facebook.com/ajax/bz. The request's `q` parameter is usually a base64-encoded tracking slug, e.g.

```
+AjwZlt7InV...9kIjoiYWpheCJ9XQ==
```
...which decodes imperfectly to 
```
f[{"user":"REDACTED","page_id":"lcw45s","posts":[["click_ref_logger",["0JEW",1525730619772,"act",68,38,"http://therin.gr/BhHpVbt","click-","r","/",{"ft":{"tn":"HHH-R-R","qJ6552957640532473528","mf_story_key":"-5982394996940170664","top_level_post_P<202696847423626628165853764441268src":10,-9nsightsB-�$:{"role":1.�d!FT�!q_contex�sfb0N�$ublish_tY$):�5H�QMiA=%m-ht`�H@q�u}dA}$0tXHP!}0ttl}lth�qh�utP}t
```

which is clearly logging the link I clicked. This happens despite blocking all `click`, `mouseup`, and `mousedown` events on the `<a>` in question. 

Chrome doesn't have this issue at all; middle- and right-click events on instrumented links don't trigger any outgoing requests. I'm stumped so far for how to block this (without intercepting the request directly), but want to bring it to your attention.

**Comment by mgziminsky** [comment]
Thanks for reporting. If it works in Chrome, then it's possible that it's a bug in Firefox itself. I'll try to investigate as well, and if I discover anything I'll be sure to let you know

**Comment by mgziminsky** [comment]
Actually, this might be it: https://developer.mozilla.org/en-US/docs/Web/Events/auxclick

**Comment by mgziminsky** [comment]
I placed a breakpoint in the FB code during the event chain for a link middle-click and stepped over every execution of their wrapper function. None of the event handlers that executed during the chains leading up the the link actually opening generated that request. A few seconds later, after execution finished and while my FB tab wasn't in focus, one of the "bz" requests appeared. They seem to appear regularly as part of some background timer or something. That being the case, I'm not sure if those requests are actually aware of the fact a link was clicked or not. My best guess at this point is that the request in question is tracking the focus on the page in some manner.

**Comment by mgziminsky** [comment]
After mousing around on the page a bit, it appears to fire whenever I focus on input fields and when hovering over names or hashtags. Some of the events also had unencoded content that suggests this might be a performance tracker. Even so, it does appear to contain specific information on where on the page you are interacting.

Since my goal is to prevent the tracking that is used for generating suggestions and ad content, I believe it is safe for me to ignore these requests. I'll leave this open until I've investigated a bit more, but as of now, I don't believe these requests are a problem.

It is strange to me though that they aren't triggered by links in Chrome. Could just be a difference in how the browsers handle focus changes, but I'm not sure.

**Comment by mgziminsky** [comment]
After more investigation, it seems this doesn't have to do with focus as I was previously hypothesizing. Unfortunately, after having no luck identifying where these events were coming from, I found this: 
https://bugzilla.mozilla.org/show_bug.cgi?id=284512

Which is one of many similar 15 year old bugs opened in FF. The one linked seems to describe what we are seeing here.

As a workaround, I'm going to play around with the event blockers on the parent of the link and see if it can be stopped there without breaking things.

**Comment by mgziminsky** [comment]
After trying a number of things, the only reliable way of preventing these requests is to block the actual request. I was able to successfully block the events by setting listeners on the window, but doing so also broke a number of things, and I couldn't find a reliable way to prevent only the event that sent these requests.

**Comment by bcyphers** [comment]
Cool. I was afraid of that, and I'm not sure if we're willing to do a blanket block like that in Privacy Badger yet. I'm going to keep digging into facebook's code to see if there's any way to filter the requests upstream, but I think this is a good approach for an aggressive blocker like this one.

**Comment by ghostwords** [comment]
@bcyphers Suggest making a demo add-on and opening a new Bugzilla issue and/or chiming in on https://bugzilla.mozilla.org/show_bug.cgi?id=284512.
