### ISSUE TITLE
Photo viewer no longer opens

### ISSUE THREAD

**Issue by mgziminsky** [mgziminsky/FacebookTrackingRemoval#12]
Clicking on a photo no longer opens the full-size image in the viewer overlay. Caused by internal link cleaning preventing click events on the images

Re-introduced in [5d8e738](https://github.com/mgziminsky/FacebookTrackingRemoval/commit/5d8e738bedc1f3501e155cc67b348f4e1bcd423e#diff-34a6d62af0cf0b784f8444529f3130efL28) while making event blocking more aggressive

**Comment by frozenpandaman** [comment]
@mgziminsky This is still happening for me unless I disable the "Remove tracking values from internal links" option. Is this expected behavior – or, is there any way around this? Thanks!

**Comment by mgziminsky** [comment]
Photo viewer still works for me right now. Is it broken everywhere for you? or just some areas? eg: feed, group pages, event pages, etc.

**Comment by frozenpandaman** [comment]
It's not specifically photo viewer that doesn't work, but that's part of it. What's happening here for me is when I click on a photo, it shows the viewer, but then immediately (before it finishes loading) the whole page refreshes (i.e. I'm taken to the photo permalink page) and then the viewer displays on top of that.

This also affects some other things, like when I click the button to tag a photo, the viewer instead refreshes, making me completely unable to tag faces in photos.

I also can't click reactions in the chat popups. Hovering over the "add reaction" button shows the popup with the reaction (emoji) choices, but clicking on any of the six emoji does nothing.

**Comment by mgziminsky** [comment]
@frozenpandaman 
Would you please open a new issue including what you said above, and as many other details as you can. I'll look into it.

Thanks

**Comment by frozenpandaman** [comment]
@mgziminsky Done.
