### ISSUE TITLE
Simple Question about The Chrome version

### ISSUE THREAD

**Issue by mikhoul** [mgziminsky/FacebookTrackingRemoval#14]
I'd like to know  why the latest version v1.5.14 is not available in the Chrome Store ?

Some specific reason or you just forgot to upload it ? 

Thanks & Regards :octocat:

**Comment by mgziminsky** [comment]
It is available in the chrome store, what are you seeing there? The status of both the FF and Chrome extension can be seen in the badges above the description on the main page: https://github.com/mgziminsky/FacebookTrackingRemoval

You can also download it directly from the releases page if you need to: https://github.com/mgziminsky/FacebookTrackingRemoval/releases

**Comment by mikhoul** [comment]
> what are you seeing there? 

I was seeing the version 1.5.13 instead of the version 1.5.14 but this morning I see the latest version 1.5.14 :+1: 

Maybe there was a delay for the ChromeStore to update the version ? 

Anyway now it's fixed :smile:    

Thanks for your quick reply and have a nice day :octocat:
