### ISSUE TITLE
Overlay input fields cannot receive focus

### ISSUE THREAD

**Issue by rcmcmullen** [mgziminsky/FacebookTrackingRemoval#15]
The "Remove tracking values from internal links" on v1.5.14 is preventing an input field on a new dialogue/overlay window from receiving focus (e.g. Friend's Birthday Overlay).  With that option selected I cannot input any text in the input field on the Overlay.

**Comment by mgziminsky** [comment]
Thanks for reporting. I'll try to look into sometime this week.
