### ISSUE TITLE
"Suggested Posts" showing up again

### ISSUE THREAD

**Issue by bayonet2** [mgziminsky/FacebookTrackingRemoval#16]
Running FF 61.0.1 on MacOS 10.13.6 and suggested posts are getting through the filter.  Filter is set on default settings.

**Comment by mgziminsky** [comment]
Thanks for reporting. There's a good chance FB is rolling out an update that changed the class used on suggested posts. They don't release updates to everybody at the same time though, and I'm not yet seeing it. I won't be able to fix it until it starts affecting me, but if you have the technical knowledge, you're more than welcome to submit a pull request.

If you want to give it a go, the hidden posts are currently just identified by a hard-coded list of selectors at the top of [src/app.js](https://github.com/mgziminsky/FacebookTrackingRemoval/blob/master/src/app.js). If you can determine the new, unique selector to use, you can edit the file and add it to the list directly in github and create a pull request.

**Comment by mgziminsky** [comment]
@bayonet2 
Is this still a problem for you? I have yet to reproduce. Are you sure you have the latest version of the extension?

**Comment by bayonet2** [comment]
Running v. 1.5.18 and it is blocking almost everything except suggested post advertisements.

**Comment by mgziminsky** [comment]
v1.5.18 had a fix to stop doing that. See #18.
