### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mikhoul** [mgziminsky/FacebookTrackingRemoval#17]
There is a bug: When I try to click on some item the click is not registered.

The best exemple is with "Stickers" when the extension is enabled I can't post stickers and as soon it is disable I can port stickers.

I'm under windows.

Regards :octocat:

**Comment by mgziminsky** [comment]
Confirmed. I will try to get it fixed some time this week.

**Comment by mikhoul** [comment]
I will test it in the next days and if I found something else I will be back. 

Regards :octocat:
