### ISSUE TITLE
Suggested Post

### ISSUE THREAD

**Issue by blwanta** [mgziminsky/FacebookTrackingRemoval#19]
I just updated to 1.5.18 and I see a "Suggested Post" for Pug Life Harness in my feed.
![screenshot_2018-08-29 facebook 1](https://user-images.githubusercontent.com/39177749/44830604-565c2d80-abd7-11e8-8a32-b18681fd25dc.png)

**Comment by mgziminsky** [comment]
This might be caused by my fix to #18, which just started for me a few hours ago. I thought my change would be backwards compatible, but maybe I was wrong.

Facebook may be rolling out an update that hasn't reached you yet. Would you try logging out and back in, and maybe clearing your cache if you know how. That may trigger you getting the update if that is the problem. Otherwise, if you could just try waiting a few days and reporting back if it still doesn't work by then.

**Comment by blwanta** [comment]
I did clean my cache, cookies, temporary files, rebooted, and logged out/in.  Yesterday, I did see more Suggested Posts, every other post practically.  As of today, it seems to be working.  I don't see any at the moment.

**Comment by blwanta** [comment]
Nevermind, they're back.

**Comment by blwanta** [comment]
Are you working on a fix for the add-on?  I am constantly see Suggested Posts and Likes (see attachment).
![screenshot_2018-09-08 facebook](https://user-images.githubusercontent.com/39177749/45260029-88684f00-b390-11e8-9941-5e900ec87c00.png)

**Comment by mgziminsky** [comment]
It's not happening for me, so I'm not able to fix it. Can you try previous
versions of the add-on and see if any of them work? If you find one that
does, let me know and I can see what changed between versions and maybe
find a fix that way

**Comment by blwanta** [comment]
I tried all the older versions up to 1.5.15.1.  Problem still persists even after deleting my cache.

**Comment by mgziminsky** [comment]
There isn't really anything I can do myself then. I'll work on adding a feature this week that will allow adding custom hiding "rules" from the options page, as well as a new file for staging user submitted rules. That way you can attempt to identify the issue on your end and easily test it. I'll include a full guide to finding an appropriate hide rule with the next release, but I'll also include a quick one below if you wanted to try fixing it yourself in the meantime.

# Guide

All hidden posts are currently just identified by a hard-coded list of selectors at the top of [src/app.js](https://github.com/mgziminsky/FacebookTrackingRemoval/blob/master/src/app.js). If you can determine the new, unique selector to use, you can edit the file and add it to the list directly in github and create a pull request.

## Finding The Selector

1. Hit CTRL+SHIFT+C to open the developer tools in inspect mode. 
1. Use your mouse to click the identifying part of the page. For suggested posts, click on the "Suggested Post" text. This will highlight the source html in the dev tools.
    - ![image](https://user-images.githubusercontent.com/1260554/45269103-ee121500-b43c-11e8-9b13-852a995c8e5d.png)
1. Look at the "class" value of the highlighted element. In the image above, it would be "b_1hcf_5oed7"
1. To get the selector/rule, combine the classes with the html element name using periods. In this case, "span.b_1hcf_5oed7". You can see the correct selector in the tooltip while hovering over the element during step 2. You can easily copy the classes by double clicking them in the tools window, which will quickly select the text for you to copy.

## Testing - Setup

1. Start by downloading the latest release source zip from the releases page, and unzipping the files to any location you want.
    - https://github.com/mgziminsky/FacebookTrackingRemoval/releases/latest
1. Download/save https://unpkg.com/webextension-polyfill/dist/browser-polyfill.min.js to the folder that you unzipped, next to manifest.json.
1. Open src/app.js in a text editor, then add your selector from the previous section to the end of the appropriate list at the top of the file.
1. Follow the appropriate instructions for your browser below to confirm your chosen selector works as expected.
- If everything works as expected, you can make the same change to [src/app.js](https://github.com/mgziminsky/FacebookTrackingRemoval/blob/master/src/app.js) directly in your browser by clicking the pencil icon in the upper right of the file. You can then submit a pull request, and I will test and merge it into the main addon.
- If it doesn't work, try again using the selector of the parent element of the one you used previously. After updating src/app.js, you'll need to reload the extension from page you loaded it in below. Repeat a few times until it works, or breaks things horribly.

### Testing - Firefox
1. Navigate to about:debugging using the url bar
1. Ensure "Enable add-on debugging" is checked, then click "Load Temporary Addon" and select the manifest.json file from the ones you unzipped in the setup section above.
1. Once the addon is shown as loaded at the top, go to your Facebook tab and reload the page to see if your new selector works.
1. To unload the temporary version when you're done, you need to restart Firefox.

### Testing - Chrome
1. Navigate to chrome://extensions/ using the url bar
1. Click "Load unpacked" in the upper left of the page and select the folder that you unzipped in the setup section above.
1. Once the addon is loaded, go to your Facebook tab and reload the page to see if your new selector works.
1. When you're done testing, you can remove the unpacked version.

**Comment by mgziminsky** [comment]
Just an update for you. I'm working on finishing up a fairly large update that will make it easier for users to submit and test hiding rules. This will mainly help in situations like yours, where the version of the site you are seeing is different from the one I see. I'm also hoping it will allow me to push updated rules without the need to update the addon. For now, you would still need to follow the first part of the guide from my last comment, but the ability to test would be built in. I'm hoping this will make it more likely that technical users will submit PRs with verified fixes for the cases I can't do myself.
