### ISSUE TITLE
Blocking friend's posts

### ISSUE THREAD

**Issue by blwanta** [mgziminsky/FacebookTrackingRemoval#21]
Your last update not only still shows Suggested Posts, but is blocking most of my friend's posts.

**Comment by mgziminsky** [comment]
The last update didn't change anything related to the blocking of posts, it was solely to address #20.

When you say "blocking" friend posts, could you be a bit more specific? You provided very few details in #19 as well, and never replied to my most recent comment.
- What settings are you using?
- If you set the "Hide Method" to collapsed, are you seeing friend posts being collapsed?
- What:
    - Device
    - Browser
    - OS
    - Extension version
- Do you have any other extensions installed that could be conflicting with mine?
- Screenshots?

I am not seeing the problem on my account, so unless you provide as many details as you can, there's no way for me to debug. It is very likely FB is serving you a different version of the site than what they give me, so there is only so much I can do.
