### ISSUE TITLE
"Remove tracking values from internal links" causes some actions to not work

### ISSUE THREAD

**Issue by frozenpandaman** [mgziminsky/FacebookTrackingRemoval#25]
**Describe the bug**
With the "Remove tracking values from internal links" options on, some components of the site break. The two I've found are the following:
- Photo viewer
  - When I click on a photo, the page starts to display the viewer, but then immediately (before it finishes loading) refreshes, i.e. I'm taken to the photo permalink page, and then the viewer displays on top of that.
  - Clicking the "Tag photo" button refreshes the page/viewer. As a result, I'm unable to tag faces in photos when the option is enabled.
- Reactions in chat popups
  - Hovering over the "add reaction" button shows the popup with the reaction (emoji) choices, but clicking on any of the six emoji does nothing.

**To Reproduce**
Enable the "Remove tracking values from internal links" and perform any of the actions described above.

**Expected behavior**
The features to behave normally, as they do with the option (or extension) disabled.

**Please provide the following information:**
Device: Desktop
OS: Mac OS X 10.11
Browser: Chrome
Extension Version: v1.6.2
Extension Options: "Inline videos on mobile" and "Add styling" options off, all others on. Hide method is "Collapse."

**Comment by mgziminsky** [comment]
I was able to fix the reactions issue, and am looking into the photo tagging issue, but am not able to reproduce the broken photo viewer in general.

I don't have access to a mac, and would be curious to know if it is a mac-specific issue. Do you have access to any non-mac computers you could try it on? If it turns out to only be an issue on macs, then there isn't a whole lot I can do on my own...

**Comment by frozenpandaman** [comment]
>I was able to fix the reactions issue

Nice, thanks! If there's a development branch I can try it out or do any testing if you need, too.

>looking into the photo tagging issue, but am not able to reproduce the broken photo viewer

My guess is that these two are related, or two instances of the same underlying thing, and that fixing one will fix the other.

>Do you have access to any non-mac computers you could try it on?

I can try it out on my work computer (if I remember). 🙂

**Comment by mgziminsky** [comment]
I've fixed what I could find. The change I made for the tagging has the possibility of fixing various other similar issues, so hopefully it was the cause of your general photo viewer issues as well.

If you still have issues after updating, see if you can reproduce on a non-mac first. If you can, then open a new issue describing what is still broken for you. If it only happens on your mac, then I won't be able to do much unless it starts happening for me as well...

**Comment by frozenpandaman** [comment]
@mgziminsky Just had a chance to test out v1.6.4 – reactions and all photo viewer-related issues are working! Yay! Thanks a ton.
