### ISSUE TITLE
Not effective with Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [mgziminsky/FacebookTrackingRemoval#28]
Follow up to https://redd.it/b9a2ww

It appears that preferences can be set, for example:

![image](https://user-images.githubusercontent.com/192271/55586213-577eab80-5720-11e9-92c0-c67d23fd8899.png)

– but settings do not persist so (for example) after navigating away from, then back to, the preferences (without closing about:addons): 

![image](https://user-images.githubusercontent.com/192271/55586356-aaf0f980-5720-11e9-8e8d-093e1ee19bb4.png)

Recently released Waterfox 56.2.8, on FreeBSD-CURRENT. 

(Waterfox 56.0 was based on Firefox 56.0.2.)

**Comment by mgziminsky** [comment]
The problem appears to be that Waterfox does not support the `finally` function on promises, which was introduced to FF in version 58. The unsupported code was added in v1.6.4 of my addon, so until Waterfox updates their API, you'll have to use v1.6.3

I'll update the min required version for the addon to reflect this. I would have done so when I made the change, but didn't notice the higher version requirement.

**Comment by MrAlex94** [comment]
If anyone is still interested, this will now be in the next release of Waterfox Classic.
https://github.com/MrAlex94/Waterfox/commit/2f7f8f654bbe2e775067030b0412a2c01cac13e4
https://github.com/MrAlex94/Waterfox/commit/dd462baf5cba9756be7b56a40094c4272c80cf0a

**Comment by grahamperrin** [comment]
Fix confirmed 👍

Thanks. 

https://www.reddit.com/comments/dmkrxs/-/f5c1rbx/
