### ISSUE TITLE
 re  facebook tracking

### ISSUE THREAD

**Issue by Murf1954** [mgziminsky/FacebookTrackingRemoval#31]
i left a  areport 20 days agao about  Facebook tracking removal and you said you need more info. well i have the info you need. was able to get a snip it od the problem that you wanted . I use Mozilla Firefox as my browser and access    facebook with a desktop icon but with   Firefox browser
 any way   this is what  i am getting 
![Capture](https://user-images.githubusercontent.com/31610875/67061251-c4dab280-f12d-11e9-993d-15b3259951ad.PNG)

**Comment by Murf1954** [comment]
just want to know how to stop this]

**Comment by Murf1954** [comment]
I HAVE TRIED TO CORRECT IT BY GOING TO ABOUT:CONFIG IN fIREFOX AND ADD TIME TO  DOM MAX SCRIPT

**Comment by Murf1954** [comment]
gues you are not going to answer me here

**Comment by mgziminsky** [comment]
I am on vacation right now and won't be able to investigate more until I get back. Spamming me is not going to make things go any faster, it will do the opposite actually.

The screenshots help, but you still haven't filled out the template with any other information it asks for. You are doing nothing to help me determine what is wrong, but somehow expect me to instantly fix everything just by barraging me with useless remarks.

Until you properly fill out the template in #30 so I can narrow things down and/or ask more questions, I am not going to waste my time.

Closed as duplicate #30
