### ISSUE TITLE
Hide inline suggestions also removes quotes

### ISSUE THREAD

**Issue by FurloSK** [mgziminsky/FacebookTrackingRemoval#33]
### Describe the bug
Turning on "Hide inline suggestions (eg: Suggested Posts, People You May Know)" feature also affects (i.e. collapses/removes) quoted text from cited articles—which probably shouldn't be treated as unwanted ad-content.

### To Reproduce
1. Find some blog/page where you can select some text and share it to FB as citation (e.g. https://www.postoj.sk/52697/pozrite-na-neho-cudaka-ma-byt-ministrom-a-pritom-veri-v-boha
2. Select some text and share it to FB
3. Go to FB and visit that specific post
4. Try turning the "Hide inline suggestions" feature off and on to see that it hides the quoted text

### Expected behavior
Quoted text from shared pages and articles shouldn't be collapsed/removed/affected by any way by the extension, as it is not an advertisement.

### Screenshots

**"Hide inline suggestions" feature turned off:**
- ![Screenshot 2020-03-20 at 00 40 20](https://user-images.githubusercontent.com/4283247/77127196-88e0ac00-6a43-11ea-93f3-7e62f4cc9a37.png)

**"Hide inline suggestions" feature turned on, with "Hide method: Collapse":**
- ![Screenshot 2020-03-20 at 00 40 41](https://user-images.githubusercontent.com/4283247/77127199-8c743300-6a43-11ea-9663-c3ff8fd0c296.png)

**"Hide inline suggestions" feature turned on, with "Hide method: Remove":**
- ![Screenshot 2020-03-20 at 00 41 00](https://user-images.githubusercontent.com/4283247/77127200-8d0cc980-6a43-11ea-8ca6-0f4bbec60633.png)

### Please provide the following information:
 - Device: Macbook Air
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome 80
 - Extension Version: 1.7.1

**Comment by mgziminsky** [comment]
Thanks for reporting, I'll look into it
