### ISSUE TITLE
Suggested Posts

### ISSUE THREAD

**Issue by Pezor** [mgziminsky/FacebookTrackingRemoval#38]
Hi,
so I'm making a brand-new post about the suggested posts, below is a screenshot from inspector, hope that helps.
![obrazek](https://user-images.githubusercontent.com/6975523/84680548-2bb9a100-af33-11ea-82e4-67c85befff4d.png)

**Comment by Pezor** [comment]
Seems like the fix isn't working for me for whatever reason as I'm still seeing suggested posts. I took another screenshot, but they look the same.
![obrazek](https://user-images.githubusercontent.com/6975523/85947987-6c131900-b94e-11ea-8a31-44f3f20f6000.png)

**Comment by mgziminsky** [comment]
Sorry, I didn't look properly at your screenshot during my last fix and missed the fact that the text you were seeing was different from me. I just added your case as well and it should work now.
