### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by gatinhonico** [mgziminsky/FacebookTrackingRemoval#39]
Hello,
Would you like i translate your addon "FacebookTrackingRemoval" in french ?

Have a nice day

**Comment by mgziminsky** [comment]
That would be great! I'll add support for translations within the next couple days, then you can submit a Pull Request adding in french.

See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization for the details on how that will work.

The TLDR is I will add a new `_locales/en/messages.json` file containing all the application text. You will just need to copy that to a new `_locales/fr/messages.json` file and translate that file.

**Comment by gatinhonico** [comment]
Ok i'm waiting you

**Comment by mgziminsky** [comment]
Ok, I've added in localization support.

If you aren't familiar with git, or don't want to clone the whole repo, you can right-click [this link to messages.json](https://github.com/mgziminsky/FacebookTrackingRemoval/raw/master/_locales/en/messages.json) and choose "Save link as..." to download the English file. Translate the values in that file, and when you're done, [follow this link](https://github.com/mgziminsky/FacebookTrackingRemoval/new/master/?filename=_locales/fr/messages.json) and drag your translated file into the editor. It should fill it with the contents of the file, and you can then commit it and submit a pull request.

The `messages.json` file covers the text shown in the extension, but the text on the listing pages in chrome and firefox is a separate thing. For that, you can just add a new comment with your translation here and I will add it to the listings.

**Comment by gatinhonico** [comment]
Hello i have made the translation 
https://github.com/mgziminsky/FacebookTrackingRemoval/compare/master...gatinhonico:patch-1

I translate the addon page
https://addons.mozilla.org/fr/firefox/addon/facebook-tracking-removal/

Removes Ads and the user interaction tracking on Facebook™. 
Modified elements can optionally have a custom CSS style applied to them so that cleaned items can be more easily identified.

Translation in french:
Supprime les publicités et la surveillance des interactions des utilisateurs sur Facebook ™. 
Les éléments modifiés peuvent éventuellement avoir une feuille de style CSS personnalisé qui leur est appliquée afin que les éléments nettoyés puissent être plus facilement identifiés.

--------------------------------------------------
Please report bugs at https://github.com/mgziminsky/FacebookTrackingRemoval/issues <https://outgoing.prod.mozaws.net/v1/7995b3debe290072b1be63440f231d15e8fb40737f9d3a36abec923fe7d93cd9/https%3A//github.com/mgziminsky/FacebookTrackingRemoval/issues>

Removes Ads and the user interaction tracking from content on Facebook™.
Modified elements can optionally have a custom CSS style applied to them so that cleaned items can be more easily identified.

For links, the event listeners on the link and its parents are removed and/or disabled and a proper href is set.

For videos on mobile, all Facebook™ event-listeners and custom controls are removed, and the video is simplified into just the bare HTML5 video tag.

Explanation of permissions: 
Access to facebook.com <https://outgoing.prod.mozaws.net/v1/3b0aa1a488ff9809554e48743a9b592944d358a0ffa3f88e394cd3ddfc36894b/http%3A//facebook.com>, messenger.com <https://outgoing.prod.mozaws.net/v1/6264b7e35deffb61e631a63efa2756d1ec25fecdb1c8280e7572b3d7dc84bbc5/http%3A//messenger.com>, and facebookcorewwwi.onion is needed for main functionality, in order to work on those pages.
Access to mgziminsky.gitlab.io <https://outgoing.prod.mozaws.net/v1/9c2accbde5f230c131d1dd3803626bfed7414a492c2e9fb5a30e0d95933c366e/http%3A//mgziminsky.gitlab.io>, more specifically https://mgziminsky.gitlab.io/FacebookTrackingRemoval/* <https://outgoing.prod.mozaws.net/v1/3c849de8ab987e7fd3b50c840ce369f98a18faffaf6938280443f7f69122e41e/https%3A//mgziminsky.gitlab.io/FacebookTrackingRemoval/%2A>, is used to download blocking rules only. No data is sent, and nothing is tracked by me.

Project is completely open source, so you are welcome, and encouraged, to check the code yourself before installing.


Translation in french:
Supprime les publicités et la surveillance des interactions utilisateur sur Facebook ™. 
Les éléments modifiés peuvent éventuellement avoir une feuille de style CSS personnalisée qui leur est appliquée afin que les éléments nettoyés puissent être plus facilement identifiés.

Pour les liens, les auditeurs d'événements sur le lien et ses parents sont supprimés et/ou désactivés et un href approprié est défini.
Pour les vidéos sur mobile, tous les auditeurs d'événements et contrôles personnalisés de Facebook ™ sont supprimés, et la vidéo est simplifiée en un simple tag vidéo HTML5.
Explication des autorisations:
L'accès à facebook.com, messenger.com et facebookcorewwwi.onion est nécessaire pour les fonctionnalités principales, afin d'appliquer des modifications sur ces pages.
L'accès à mgziminsky.gitlab.io, plus spécifiquement https://mgziminsky.gitlab.io/FacebookTrackingRemoval/*, est utilisé pour télécharger uniquement les règles de blocage. Aucune donnée n'est envoyée, et rien n'est surveiller de ma part.

Le projet est complètement open source, vous êtes donc les bienvenus et encouragés à vérifier le code vous-même avant l'installation.


--------------------------------------------------
Would you like i translate the chagelog too ?

Have a good day Michael
-- 
 Envoi sécurisé avec Tutanota. Obtenez votre propre adresse email chiffrée : 
 https://tutanota.com


6 juil. 2020 à 23:58 de notifications@github.com:

**Comment by mgziminsky** [comment]
Perfect, thanks! Don't worry about the changelog since it is updated so often, it's easy enough for the people that care to run just that through a translator on their own.
