### ISSUE TITLE
Thanks.

### ISSUE THREAD

**Issue by urza** [mgziminsky/FacebookTrackingRemoval#41]
Hi there. I didnt find a way how to contact you, so sorry for putting it here under issues. Just wanted to say thank you for writing this extension. It works great. It can hide sponsored posts from my timeline even in cases when uBlock Origin fails. Kudos to you guys. 
Cheers
urza

**Comment by mgziminsky** [comment]
Thanks, your gratitude is appreciated.

If you haven't already, the best way to show your support would be to leave a review on the Firefox and/or Chrome extension pages.
