### ISSUE TITLE
Hiding Friends Like With Hidden Ads

### ISSUE THREAD

**Issue by aeallord** [mgziminsky/FacebookTrackingRemoval#45]
**Describe the bug**
The problem I'm encountering, a person on my Friends List is being hidden behind the arrow/title to view content mask. 

**To Reproduce**
There are no "steps to reproduce" because it is a person on my friends list. I am including screenshots of what happens to the list of friends online when he appears in the list and a screenshot from when I go visit his page. There is no current post of his appearing in my timeline so I can't show what is happening there, but the results are the same with the arrow/title and then opening by clicking on the arrow.

**Expected behavior**
Friends posts shouldn't be hidden

**Screenshots**
![Screen Shot 2020-10-30 at 6 23 59 PM](https://user-images.githubusercontent.com/13206762/97768209-bfed6480-1ade-11eb-9558-dd3b7e786a5b.jpg)
![Screen Shot 2020-10-30 at 6 24 10 PM](https://user-images.githubusercontent.com/13206762/97768210-c7ad0900-1ade-11eb-9a30-2192e3b884bd.jpg)
![Screen Shot 2020-10-30 at 6 29 13 PM](https://user-images.githubusercontent.com/13206762/97768212-cbd92680-1ade-11eb-92d6-a64bb30f6639.jpg)
![Screen Shot 2020-10-30 at 6 33 04 PM](https://user-images.githubusercontent.com/13206762/97768215-cf6cad80-1ade-11eb-9fd8-da57d273ae26.jpg)

**Please provide the following information:**
 - MacBook Pro
 - Firefox and Chrome

**Additional context**

**Comment by mgziminsky** [comment]
Thanks for reporting.

To find the source of the issue, enable logging under advanced options and disable the external and internal link cleaning options. then enable only the sponsored option and suggestions option individually to see which one is causing it. With just the problem option enabled, send me the relevant console logs.

This has happened occasionally in the past as FB starts re-using old css classes and such that were previously used exclusively for ads. I've moved on to a more robust method for detecting ads and suggestions, but I was waiting to remove the old code until the redesign had been fully rolled out.

I'm assuming you are a technical user based on your site linked in your github profile, but if that's not the case I can give more detailed instructions on how to obtain the information I'm looking for.

**Comment by aeallord** [comment]
Thanks for getting back to me… 

Here is what I have logged from Sponsored Articles option only being selected



Here is from the Hide Inline Suggestions option only being selected



Looks like the Hide Sponsored Posts is causing the issue.

Please let me know if you would like additional debugging on my end. Your assumption is correct, my day job is as a software engineer… Glad to help with any diagnosis with this issue.

-Andy

**Comment by mgziminsky** [comment]
Well crap, the problem is your friends name lol

My simple and naive way of detecting ads is to just take the unique characters of the labels I want to hide and use that as a simple key. Your friends name is made up of the same letters that spell "Sponsored." I'm apparently not taking spaces into consideration currently, so that may be an easy fix, but I figured something like this would happen eventually.

I'll play around with it when I have time this weekend and should have a fix sometime soon.
