### ISSUE TITLE
[Ads] Suggested Pages

### ISSUE THREAD

**Issue by Pezor** [mgziminsky/FacebookTrackingRemoval#47]
Hi,

so Facebook must have changed something recently, as I started seeing these, once again. Could you look into it?

Class values, adding this fixed the issue for me:
`d2edcug0 hpfvmrgz qv66sw1b c1et5uql oi732d6d ik7dh3pa fgxwclzu a8c37x1j keod5gw0 nxhoafnm aigsh9s9 ns63r2gh fe6kdd0r mau55g9w c8b282yb iv3no6db o3w64lxj b2s5l15y hnhda86s m9osqain`

![obrazek](https://user-images.githubusercontent.com/6975523/110232345-4dbdde00-7f1d-11eb-92a0-5827fa8139f1.png)

**Comment by mgziminsky** [comment]
Already fixed by c9648a1. Try refreshing your blocking rules with the button under the advanced options or restarting your browser.
