### ISSUE TITLE
Unable to attach pictures to comments

### ISSUE THREAD

**Issue by ToniA** [mgziminsky/FacebookTrackingRemoval#49]
**Describe the bug**
When the extension is enabled, attaching pictures to comments of posts does not work. The upload does not progress from 0%

**To Reproduce**
1. Go to any post you would like to comment
2. Start writing a comment
3. Either attach a picture or paste a picture from clipboard
4. The picture upload never completes, progress stays at 0%

**Expected behavior**
Pictures can be uploaded to comments. Upload works if the extension is disabled.

**Please provide the following information:**
 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome 90.0.4430.212 (Official Build) (64-bit)
 - Extension Version: 1.9.2

**Comment by nnardo** [comment]
Can confirm this behavior too.

- Device: Laptop
- OS: Windows 10 (20H2)
- Browser: Firefox 88.0.1 (64-bit)
- Extension Version: 1.9.2

**Comment by mgziminsky** [comment]
Thanks for reporting, I'll look into it.
