### ISSUE TITLE
Breaks functionarlity for editing / deleting comments & Skipping forwards and backwards in Videos

### ISSUE THREAD

**Issue by ravenise** [mgziminsky/FacebookTrackingRemoval#5]
I made a video showing the bug here! https://vimeo.com/247662650

Using the latest FF quantum 57.0.2 (64-bit) on Windows 7 SP3 64.

doesn't show the mouse but i assure you i am clicking on the video and the rest.

Also causes tab to jump to the top of the window when trying to edit/delete most comments.

Remove tracking from external links (disabling this allows videos to skip forward/backward and removes the jumping to top of the page;

Disabling removing tracking from INTERNAL link removes the annoying dotted outline around all the elements in facebook

disabling all ADDONS but yours, I still had the same issue; interestingly some videos were able to skip forwards and backwards, and others were not.

**Comment by ravenise** [comment]
doesn't show the mouse but i assure you i am clicking on the video and the rest.

**Comment by ravenise** [comment]
Also causes tab to jump to the top of the window when trying to edit/delete most comments.

**Comment by ravenise** [comment]
Remove tracking from external links (disabling this allows videos to skip forward/backward and removes all of the other issues, as well as the annoying dotted outline around all the elements in facebook)

**Comment by ravenise** [comment]
FF quantum 57.0.2 (64-bit)

**Comment by ravenise** [comment]
Disabling removing tracking from INTERNAL link removes the annoying dotted outline around all the elements in facebook

**Comment by mgziminsky** [comment]
Thanks! I'll try to look into all of those this week.

Just FYI, the dotted outline can be disabled by unchecking the "Add styling..." option. It is there to tell you which things the addon has made changes to

**Comment by ravenise** [comment]
disabling all ADDONS but yours, I still had the same issue; interestingly some videos were able to skip forwards and backwards, and others were not.

**Comment by ravenise** [comment]
I can test this in linux mint 64 for you also, give me a moment.

**Comment by ravenise** [comment]
Thank you!

**Comment by mgziminsky** [comment]
No need to test elsewhere, everything you described is very likely to be caused by my addon, and the OS doesn't really matter. I have a good idea as to the cause of most of it as well.

**Comment by ravenise** [comment]
Thank you! Exact same problems replicated in 57.0.1+linuxmint1+rosa

**Comment by ravenise** [comment]
I highly recommend the styling to be disabled by default; it will detract a lot of users; your addon is the best, smallest, most efficient and safest by a long shot, but it just needs a little ironing out. Get it fixed while everybody is catching up with quantum & you'll be at the top of the list.

**Comment by mgziminsky** [comment]
Thanks :) I'll consider disabling the styling by default this next release.

If you'd be willing to continue helping out, I can start releasing beta versions, or you could get the direct source as I update it here, and you could test for me.
I'm not much of a FB user, so having a more typical user willing to put the addon through a full workload and then report back their findings would be an immense help.

**Comment by ravenise** [comment]
sure just let me know where and how I can be of service my brother, thank yhou.

**Comment by mgziminsky** [comment]
Are you using the latest version of the addon? I haven't managed to reproduce any of those issues... All links, buttons, etc. work as expected for me. I tested using a clean profile having only my addon in the current stable Firefox.

**Comment by ravenise** [comment]
1.5.3 direct from mozilla

**Comment by ravenise** [comment]
ive never compiled ghithub code, don't know a thing about it.

**Comment by mgziminsky** [comment]
If you have the latest version, I'm not sure what to do. I can't reproduce any of the things you reported.

Nothing needs to be compiled. You can run it from the source by doing the following:
- Download the firefox branch as a zip file: https://github.com/mgziminsky/FacebookTrackingRemoval/archive/Firefox.zip
- Unzip it somewhere
- Go to about:debugging in Firefox
- Choose "Load Temporary Addon"
- Select the manifest.json file in the files that were unzipped

More info can be found at https://developer.mozilla.org/en-US/docs/Tools/about%3Adebugging
Loading a temporary addon in particular

I haven't changed anything though, so what is on github is identical to what is in the published addon right now.

**Comment by ravenise** [comment]
doesn't look like i can help you my brother

**Comment by mgziminsky** [comment]
I am still unable to reproduce this, so I'm going to close. If I receive any more reports, or manage to reproduce on my own, I'll re-open.
