### ISSUE TITLE
shop ads

### ISSUE THREAD

**Issue by Pezor** [mgziminsky/FacebookTrackingRemoval#50]
Hi,
I started seeing these shop ads, can you update the rules to block them? Thanks
![obrazek](https://user-images.githubusercontent.com/6975523/136029376-c55f7bc8-5bce-4735-81b4-c4c012b5655c.png)

**Comment by Pezor** [comment]
Unfortunately does not for me.

**Comment by mgziminsky** [comment]
Should be fixed in latest release (v1.10.0.1)
