### ISSUE TITLE
Random Newsfeed crashes

### ISSUE THREAD

**Issue by jarredou** [mgziminsky/FacebookTrackingRemoval#54]
**Describe the bug**
After some minutes using the addon, the newsfeed crashes and is replaced by facebook's "Something went wrong" error message.

**To Reproduce**
1. Go to facebook.com
2. scroll down the newsfeed for few minutes
3. until it crashes

**Expected behavior**
no crash

**Screenshots**
![facebook bug](https://user-images.githubusercontent.com/6044199/176675177-78cf3776-cced-426c-9734-e7faea994781.png)

**Please provide the following information:**
 - Device: Desktop
 - OS: Win7 64
 - Browser : Firefox Dev 103.0b2 (64 bits)
 - Extension Version : 1.10.0.1
 - Extension Options : see screenshot

**Additional context**
Ublock Origin & Facebook purity disabled
It seems to be related to the error shown in the screenshot, in Firefox's console, that is happening at the same time of the bug.
The network tab of the console shows that there are also some calls to "https://www.facebook.com/ajax/bulk-route-definitions/"  happening at the same time.

**Comment by mgziminsky** [comment]
Thanks for the detailed report. I am able to reproduce and have a theory as to what is happening.
I was also able to confirm this is only an issue with the "Hide Method" set to "Remove", so as a temp workaround you can change it to Collapse mode.

**Comment by jarredou** [comment]
Ok. Thanks for the workaround !

**Comment by mgziminsky** [comment]
Fixed in `v1.10.1`
