### ISSUE TITLE
Remove "Reel and short videos"

### ISSUE THREAD

**Issue by NguyenASang** [mgziminsky/FacebookTrackingRemoval#56]
**Describe the feature request**
Add an option to remove "Reel and short videos" appear in [main Facebook page](https://www.facebook.com/).

**To Reproduce**
1. Go to https://www.facebook.com
2. Scroll down to until you see "Reel and short videos" (it appears randomly)

**Screenshot** 

![image](https://user-images.githubusercontent.com/87893636/181919494-cf092f25-c15a-4de4-bddb-e875e0266e1f.png)

**Additional context**
Thank you for reading my previous report and fixing the issues, hope you can take a look at my feature request.

**Comment by mgziminsky** [comment]
You need to enable the "Hide inline suggestions" option to remove those.

**Comment by NguyenASang** [comment]
@mgziminsky But I don't want to remove "Suggested Posts". Can you add a separate option?

**Comment by mgziminsky** [comment]
Sorry, i'm not going to add an option for just that. In the future I may make it possible to enable/disable each rule individually, but I have no immediate plans to do so.

One option would be to enable hiding suggestions and switching the mode to "Collapse" so you still have access to everything that is hidden. 

Another option is to add `h3,span[dir]||Reels and short videos` to the advanced option for "Custom CSS selectors." I just realized this option is currently broken though, so it won't work until i release a new version with a fix.
![image](https://user-images.githubusercontent.com/1260554/182006202-0e013391-45c3-48ab-8de3-66403a591dfa.png)

**Comment by NguyenASang** [comment]
Yes the "Custom CSS selectors" is broken, hope you can fix it in the next release.

**Comment by sandebert** [comment]
> You need to enable the "Hide inline suggestions" option to remove those.

I'll just note that I do have that enabled and I still see the reels and short videos. 

I can't tell if it's relevant, but I'll add that I'm using Swedish FB, where it's called "Reels och korta videor".

**Comment by mgziminsky** [comment]
> I'll add that I'm using Swedish

@sandebert I only have the English version of most suggestions, so that is definitely your issue. I will add the translation you provided, and if there are any other Swedish variations, it would help if you would add them to the file [data/hide_rules/suggested/texts](https://github.com/mgziminsky/FacebookTrackingRemoval/blob/master/data/hide_rules/suggested/texts) and submit a PR.
