### ISSUE TITLE
Certain FB functionality breaks with extension enabled

### ISSUE THREAD

**Issue by poiromaniax** [mgziminsky/FacebookTrackingRemoval#62]
Hi there,

Im a new user to the extension - glad I found it! The tracking was driving me nuts (now I just need this for FB app/safari on iOS!)

I have found 2 issues on FB though, these are only resolved by disabling the extension totally. (I tried disabling the options 1 by 1 to see if its fixed)

1) Mentioning someone in a post/comment does not bring up the username selector
2) Switching profiles (I manage a group and interact with the group as a page. The "interact as" popup loads, but clicking on the other profile does not work)

**Comment by sinyo1015** [comment]
Bump, I also get similar problems as you mentioned

**Comment by mgziminsky** [comment]
Thanks for reporting, I'll look into it this week.
