### ISSUE TITLE
Migration to Manifest V3

### ISSUE THREAD

**Issue by ntx61** [mgziminsky/FacebookTrackingRemoval#63]
Chrome's MV3 migration is coming fast. To continue supporting Google Chrome (and other Chromium-based browsers), are there any plans to migrate this extension to use Manifest V3?

With the [current plan by Google](https://developer.chrome.com/blog/more-mv2-transition/) (EDIT DEC 2022: Currently postponed and under review):

* Manifest V2 starts to sunset in around 2 months' time (January 2023), when Chrome starts disabling MV2 extensions in non-Stable channels and MV3 becomes a requirement to have a Featured badge in Chrome Web Store.
* Starting in June, Chrome starts disabling MV2 extensions in all channels and Chrome Web Store hides all existing public MV2 extensions.
* Sunsetting completes in January 2024, when the Chrome MV2 enterprise policy expires and all existing MV2 extensions in Chrome Web Store are taken down.

While other Chromium-based browsers may have their own timelines in MV2 deprecation (and may allow installations of `*.crx` files), if the upstream Chromium codebase removes MV2 support sometime after 2023, they may eventually have to drop MV2 support if maintenance costs too much time for devs of downstream Chromium-based browsers.

While Firefox is [yet to catch up](https://blog.mozilla.org/addons/2022/10/31/begin-your-mv3-migration-by-implementing-new-features-today/) with supporting MV3, some MV3 features are already available in Firefox MV2.

**Comment by mgziminsky** [comment]
I do intend to eventually migrate to v3 once Firefox fully rolls out their implementation. Once that happens, the Chrome version will be limited in comparison and I may decide to stop supporting Chrome altogether at any point.

I recommend switching over to Firefox or Librewolf now if you want continued support.

**Comment by mgziminsky** [comment]
Closed with [`437d036`](https://github.com/mgziminsky/FacebookTrackingRemoval/commit/437d0367c75356760979371854af07885130cba4)
