### ISSUE TITLE
Android | External URLs not clickable

### ISSUE THREAD

**Issue by Migliutin** [mgziminsky/FacebookTrackingRemoval#7]
On Android the posts pointing to external URLs become not-clickable.
This makes the addon unusable.

**Comment by mgziminsky** [comment]
Thanks for reporting. I'll look into it. 

Until this is fixed, if you still wanted to use it for the adblocking and internal tracking, you can disable the just the external link processing from the addon options.

**Comment by mgziminsky** [comment]
Fixed in v1.5.6
