### ISSUE TITLE
Ads blocking has been detected by FB

### ISSUE THREAD

**Issue by NguyenASang** [mgziminsky/FacebookTrackingRemoval#71]
## Screenshot
![image](https://user-images.githubusercontent.com/87893636/218302990-a5922f2d-d9b9-4b6f-93a0-657cbd817a53.png)

**Comment by mgziminsky** [comment]
Haven't seen that before lol The extension is working as intended and shouldn't be blocking any legit posts, so FB is just trying to scare people. The fact they can detect it though could be somewhat of an issue.

Do you happen to have any other ad block extensions installed? And what browser are you using?

**Comment by NguyenASang** [comment]
> Do you happen to have any other ad block extensions installed?

No, I disabled all of them except yours.

> And what browser are you using?

Edge version 110.0.1587.41

**Comment by NguyenASang** [comment]
> Well, I have a script called "Adguard Extra (Beta)" enabled, still need time to find the culprit.

Look like that's the culprit, close this.

**Comment by NguyenASang** [comment]
But I want to remove "People you may know" only, what's the rule to remove it ?
