### ISSUE TITLE
Changes are not applied -- "Changes will be applied when this options page is closed"

### ISSUE THREAD

**Issue by raidenGitHub** [mgziminsky/FacebookTrackingRemoval#78]
**Describe the bug**
I have uninstalled and re-installed the extension on Firefox, but every time that I open the "Options" for the add-on, every option is unchecked.   I check the options, close the page, but the check-boxes are empty again the next time I open "Options".  This affects only one of my computers with Firefox, but not the other computer.     All permissions are granted to the addon, but all Options are disabled permanently. I'm not sure how to enable the options, or what to do to fix it. 

**To Reproduce**
From Debug Address:   "about:debugging#/runtime/this-firefox" > "Tracking & Ad Removal on FaceBk" > Inspect > Console: 

```
Uncaught TypeError: storage.onChanged is undefined
    <anonymous> moz-extension://cce130d4-eca7-4461-bfa1-8c88e083cc7d/src/config.js:207
[config.js:207:1](moz-extension://cce130d4-eca7-4461-bfa1-8c88e083cc7d/src/config.js)
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://cce130d4-eca7-4461-bfa1-8c88e083cc7d/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map
```

**Expected behavior**
I expect the "Suggested for you" entries to be collapsed like the other good computer, but none of the entries are collapsed, and all options from add-on stuck in unchecked.

**Screenshots**

![image](https://github.com/mgziminsky/FacebookTrackingRemoval/assets/16138546/25625314-da17-4362-a9ec-5e359bf8ac75)

**Please provide the following information:**
 - Device:  Laptop
 - OS: Windows 11
 - Browser Firefox
 - Extension Version 1.11.3
 - Extension Options > Unchecked, Can't check because the options do not save after closing.

**Comment by mgziminsky** [comment]
What version of Firefox are you using? Have you somehow disabled extension storage or something in the browser? That is a browser api, and should always be present.

**Comment by raidenGitHub** [comment]
Hi mgziminsky, thanks so much for your suggestion.   My version of Firefox was 96.0.3 and the automatic updater did not find an update (in Help>About Firefox).  I manually downloaded and updated my Firefox version to 121.0 and that fixed the issue. 

Thanks for your help!
