### ISSUE TITLE
Sponsored and suggested contening shown again

### ISSUE THREAD

**Issue by arcus80** [mgziminsky/FacebookTrackingRemoval#79]
# Requests about ads not being hidden will be closed without response. Follow the instructions in the "Ad blocking support" template for that.

**Describe the bug**
I'm pretty sure this would go here since it's a separate feature from ad blocking, but I do apologize if I was incorrect.  When opening my browser and going to Facebook.com I have noticed in the last three days or so that sponsored articles and suggested topics, posts, comments have returned to my feed.  I checked to make sure that "Hide inline suggestions (eg: Suggested Posts, People You May Know)" and "Hide Sponsored articles" are still checked and they are.  I refreshed them and tried restarting everything but to no avail.  I tried enabling any pending or unconfirmed rules in the advanced options.  Advertisements are still being hidden just fine, it's only sponsored articles and suggested content.  This happens whether or not I go to the main page or go to the "Feeds" feature.  I also tried hiding instead of collapsing but it didn't work either.  The text that says "Sponsored" and the triangle that you click to uncollapse remains there but the post is visible no matter what. 

**To Reproduce**
1. Go to Facebook.com
2. Click on nothing or choose Feeds
3. Scroll down to see the sponsored and suggested items in the feed ever couple posts or more. 

**Expected behavior**
Prior to this issue I didn't see sponsored or suggested content.  It was collapsed in my feed.  
**Screenshots**

**Please provide the following information:**
 - Device: Acer Nitro 5 Laptop
 - OS: Windows 11
 - Browser Firefox 120.0.1
 - Extension Version v1.11.3
 - Extension Options The following options are enabled: Remove tracking from external links, Hide Sponsored articles, Hide method "Collapse", Enable pending/unconfirmed hiding rules

**Additional context**
![Screenshot 2023-12-15 at 19-42-56 Facebook](https://github.com/mgziminsky/FacebookTrackingRemoval/assets/153718041/3e671f25-10a1-4731-8dbf-b173e29eb63f)
![Screenshot 2023-12-15 at 19-43-17 Facebook](https://github.com/mgziminsky/FacebookTrackingRemoval/assets/153718041/ecc6e615-c7d2-4505-8242-f701793115e7)

**Comment by mgziminsky** [comment]
I'm not able to reproduce on my end, so there's not much I can do for now. FB has been doing some experiments to avoid ad blockers recently, so you probably ended up in one of the test groups. 

I was in one of the test groups a couple months ago and was working on a fix, but their test ended before I finalized my solution. If you're lucky, they will finish their test after about a week and things will just start working again, or in the case it gets rolled out to everyone, I will fix it once it starts affecting me.

**Comment by arcus80** [comment]
I understand and thank you very much!

**Comment by mgziminsky** [comment]
They pushed the change to me. It should now be fixed. You just need to perform a rules update by either restarting your browser, or by forcing an updating by clicking the "Refresh Rules" button under the advanced options while holding the CTRL key.
