### ISSUE TITLE
Suggestions showing up

### ISSUE THREAD

**Issue by arcus80** [mgziminsky/FacebookTrackingRemoval#89]
# Requests about ads not being hidden will be closed without response. Follow the instructions in the "Ad blocking support" template for that.

I assume this is separate since it's a separate feature, my apologies if I misunderstand though. 

**Describe the bug**
When looking at my feed group suggestions and also other user's activity shows up again.  No ads showing up or anything, but just group suggestions and things like "So and So commented on..."
**To Reproduce**
1. Go to ['...'](https://www.facebook.com/)
2. Click on '....' You don't have to click on anything just scroll the feed. 

**Expected behavior**
Normally suggested groups are hidden with other suggested posts. 

**Screenshots**

**Please provide the following information:**
 - Device: Desktop
 - OS: Windows 11
 - Browser Firefox, latest version
 - Extension Version 1.13.0
 - Extension Options All options except "Inline videos on mobile (Only affects mobile; May increase data usage)" and also no custom CSS

**Additional context**
This started about a week ago, but I didn't rush to report it just to make sure it didn't resolve on it's own.  Thank you for this extension because it's the only thing that makes Facebook usable.

**Comment by mgziminsky** [comment]
I added a potential fix to the pending rules. Would you mind enabling the pending rules option under the advanced options then refresh rules if possible or restart your browser.

After a couple days let me know if the issue was fixed or if you saw any issues. If it works correctly, I'll publish it to the main rules list.

**Comment by arcus80** [comment]
> I added a potential fix to the pending rules. Would you mind enabling the pending rules option under the advanced options then refresh rules if possible or restart your browser.
> 
> After a couple days let me know if the issue was fixed or if you saw any issues. If it works correctly, I'll publish it to the main rules list.

Sure, no problem, I'm already not seeing suggested posts. I'll keep an eye on it for a couple days and let you know.  Thank you!

**Comment by arcus80** [comment]
> I added a potential fix to the pending rules. Would you mind enabling the pending rules option under the advanced options then refresh rules if possible or restart your browser.
> 
> After a couple days let me know if the issue was fixed or if you saw any issues. If it works correctly, I'll publish it to the main rules list.

Hey there, I haven't seen any issues.  Also not seeing any suggestions or so and so commented on type of posts.  Thank you so much!
