### ISSUE TITLE
I see Suggested Posts

### ISSUE THREAD

**Issue by blwol** [mgziminsky/FacebookTrackingRemoval#9]
I still see "Suggested Posts".  

![2018-0427_092941](https://user-images.githubusercontent.com/38494291/39373797-8fc4336a-49fd-11e8-9ed8-965d1f74a8b1.png)

Firefox 59.0.2 (32 bit)

**Comment by mgziminsky** [comment]
@blwol 
I just released a fix for the new "Sponsored" articles. If the latest version fixes the problem then let me know and/or close this issue.

**Comment by mgziminsky** [comment]
Closing due to no response
